# Generated by Django 4.1.7 on 2023-02-22 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=50, null=True)),
                ('uniq_Opnd', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(7.9)])),
                ('total_Op', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(4.4)])),
                ('total_Opnd', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(6.9)])),
                ('branchCount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-0.8), django.core.validators.MaxValueValidator(2.5)])),
                ('predictions', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
