# Generated by Django 4.1.7 on 2023-03-19 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("software_id", models.CharField(max_length=50, null=True)),
                ("license_key", models.CharField(blank=True, max_length=50)),
                ("hashvalue", models.CharField(max_length=256, null=True)),
                (
                    "branchCount",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-0.8),
                            django.core.validators.MaxValueValidator(2.5),
                        ],
                    ),
                ),
                (
                    "predictions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Status"),
                            ("Bugs", "Bugs"),
                            ("Genuine", "Genuine"),
                            ("Pirated", "Pirated"),
                        ],
                        default="Status",
                        max_length=50,
                    ),
                ),
                ("tested_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "data",
                "verbose_name_plural": "data",
                "ordering": ["-tested_at"],
            },
        ),
        migrations.CreateModel(
            name="Predictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("softwarename", models.CharField(max_length=50, null=True)),
                ("licensekey", models.CharField(max_length=50, null=True)),
                ("Hashvalue", models.CharField(max_length=50, null=True)),
                (
                    "branchCount",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ("Predictions", models.CharField(blank=True, max_length=50)),
                ("Tested_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "predictions",
                "verbose_name_plural": "predictions",
                "ordering": ["-Tested_at"],
            },
        ),
    ]
