# Generated by Django 4.1.7 on 2023-03-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_data_predictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-tested_at']},
        ),
        migrations.RenameField(
            model_name='data',
            old_name='date',
            new_name='tested_at',
        ),
    ]
