# Generated by Django 4.1.7 on 2023-03-10 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_data_options_rename_date_data_tested_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='branchCount',
            new_name='license_key',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='software_name',
            new_name='software_id',
        ),
        migrations.AddField(
            model_name='data',
            name='hashvalue',
            field=models.CharField(default=datetime.datetime(2023, 3, 10, 3, 52, 40, 639002, tzinfo=datetime.timezone.utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='predictions',
            field=models.CharField(choices=[('', 'Status'), ('bugs', 'bugs'), ('unpirated', 'unpirated'), ('pirated', 'pirated')], default='Status', max_length=50, null=True),
        ),
    ]
