# Generated by Django 4.1.7 on 2023-03-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_branchcount_data_license_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='hashvalue',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='license_key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
