# Generated by Django 4.1.3 on 2023-03-16 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_data_hashvalue_alter_data_license_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='total_Op',
        ),
        migrations.RemoveField(
            model_name='data',
            name='total_Opnd',
        ),
        migrations.RemoveField(
            model_name='data',
            name='uniq_Opnd',
        ),
        migrations.AddField(
            model_name='data',
            name='branchCount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.5)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='predictions',
            field=models.CharField(choices=[('', 'Status'), ('Bugs', 'Bugs'), ('Genuine', 'Genuine'), ('Pirated', 'Pirated')], default='Status', max_length=50, null=True),
        ),
    ]
